### ISSUE TITLE
How do I suspend a Business Process before a UserTask begins?

### ISSUE THREAD

**Issue by ongbt** [roger-castaldo/BPMEngine#12]
Thanks for creating this library.

I am trying to integrate this library into web app but I have an issue.
How do I detect that a UserTask is starting and to suspend the Task while waiting for user input?
I know about bp.BeginUserTask but in the delegate I do not have a reference the business process.

**Comment by roger-castaldo** [comment]
When that delegate function is called the process will naturally suspend that path because it is waiting on you to call the complete or error delegate callback.  Each of those callbacks are instance specific and will therefore will invoke on the specific business process that called it.  

If you need to actually reference the process, one option would be to assign it some sort of ID and set it as a process variable as that would allow you a way to find that instance.  Another option would be to implement a wrapper class around the business process that sets those delegates as instance specific and would hold the business process as a private variable.
