### ISSUE TITLE
Can U provide exmples 

### ISSUE THREAD

**Issue by Diaskhan** [roger-castaldo/BPMEngine#4]
Hie, its very interesting !
1.Can U provide examples of Usage ??
2.BPM engine depends on WF library, or its a clear BPMN ?
3. What about persistent ? what library do U using for persistent, ef core, nhibernate ?

**Comment by roger-castaldo** [comment]
1.  Attached is a sample bpmn diagram that would run a vacation request with some validation built in the the library can handle.  Outside of the built in components, you would need to implement delegates to handle the different user tasks that get assigned throughout.  
[VacationRequest.zip](https://github.com/roger-castaldo/BPMEngine/files/1334887/VacationRequest.zip)


2.  The engine is completely independent the only real thing required is Jint.dll to handle javascript calls from the system when used.  Otherwise it is purely bpmn 2.0 compliant no wf library usage.

3.  Persistence is designed in a purely black box method.  The state of the process is stored as an xml document, of which there is a delegate that gets called when the state changes providing a new version of the document.  What you do with the document outside of the library is your call.  It was designed this way for autonomy in that the library does not care how your build the process or how you interact with the process on the other side of the delegates, or even what you do with the state document, it simply runs the process.
